server:
  additionalApplications:
   - name: cluster-config
     namespace: argocd
     project: default
     source:
       repoURL: https://github.com/NVB20/chatroom-helm.git
       targetRevision: HEAD
       path: ""
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
     extraArgs:
      - --insecure