server:
  additionalApplications:
   - name: app-argo
     namespace: argocd
     project: default
     source:
       repoURL: https://github.com/NVB20/chatroom-helm.git
       targetRevision: HEAD
       path: "chatroom"
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
     extraArgs:
      - --insecure
   - name: mongo-argo
     namespace: argocd
     project: default
     source:
       repoURL: https://github.com/NVB20/chatroom-helm.git
       targetRevision: HEAD
       path: "mongo"
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
     extraArgs:
      - --insecure
   - name: grafana-argo
     namespace: argocd
     project: default
     source:
       repoURL: https://github.com/NVB20/chatroom-helm.git
       targetRevision: HEAD
       path: "grafana"
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
     extraArgs:
      - --insecure